name: create PR from private

on:
  workflow_dispatch:
    inputs:
      private_pr_number:
        required: true

jobs:
  make-pr:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Get PR patch
        run: |
          PR_NUMBER=${{ github.event.inputs.private_pr_number }}
          OWNER=colobas
          REPO=dummy-private-repo

          curl -o ../private-pr.patch \
              -L \
              -H "Accept: application/vnd.github.patch" \
              -H "Authorization: Bearer ${{ secrets.READ_PRIVATE_PR_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUMBER"

      - name: Run a multi-line script
        run: |
          git apply --3way --ignore-space-change \
          --exclude '.github/**' \
          --exclude 'configs/local/**' \
          ../private-pr.patch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PULL_REQUEST_TOKEN }}
          branch: pr-from-private-repo/${{ github.event.inputs.private_pr_number}}
          commit-message: |
            Applying changes from private repo PR #${{ github.event.inputs.private_pr_number }}
