name: dispatch private workflow

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger private workflow
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/github-script@v6
        with:
          #script: ${{ secrets.PRIVATE_WORKFLOW_SCRIPT }}
          github-token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'colobas',
              repo: 'dummy-private-repo',
              workflow_id: 'create-pr-from-public.yml',
              ref: 'main',
              inputs: {
                public_pr_number: ${{ github.event.pull_request.number }}
              }
            })
            console.log(result)
